name: CI
on:
  push:
    branches: [ main, setup-task ]
  pull_request:
    branches: [ main ]
jobs:
  eda:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "Contents of requirements.txt:"
          cat requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "requirements.txt not found"; exit 1; fi
      - name: List files
        run: ls -R
      - name: Display Python version
        run: python --version
      - name: Display installed packages
        run: pip list
